#server:
#  undertow:
#    io-threads: 16
#    worker-threads: 256
#    buffer-size: 1024
#    direct-buffers: true
spring:
  application:
    name: lab-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.47.128:3306/physician?charset=utf8
    username: centos
    password: 123456
mybatis-plus:
  type-aliases-package: com.medical.entity
  mapper-locations: classpath:mapper/medical/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:8088/eureka
    register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
    fetch-registry: false # 是否拉取其它服务的信息，默认是true
  server:
    eviction-interval-timer-in-ms: 60000 # 扫描失效服务的间隔时间（缺省为60*1000ms

alipay:
  url: https://openapi.alipaydev.com/gateway.do
  #此处请填写你当面付的APPID
  appid: 2021000121648216
  #此处请填写你的应用私钥且转PKCS8格式
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCF6cRPC+O/5oTCxFJ9F8vaEP/FwGFUaJbmuLzgTqkZm3xvGq5Sm1IAXvyQEgMiTUS5cQEf0JHEWvnVqdBqOkKVh5e36XvFWIZmzY7f4xXlOYVKUnZg1wHKgBH/hiMkVTOi0LdvzVTjFejkAo2AeP8OgfRMDJUVdBhzz/f6YXyQJb6aHHQ6VXTkd9SCKz1jizymhu7+PC0pdYo88M35t6+Zg7Wm1+9h7SK/xcxz/XXLZAjap0gV5/QivFXpqWuti1RjA0uiridGBiwz/23raiSdkkF9IxTSjaaVfdovkYkcnDngn+cBRti/stYZ3aEUOjnES9e2xlSBGOtw8xYPSmGHAgMBAAECggEAYy5HSfBZZzj5XTOAkMu+HK14cmNQ8u5fzVRH963qyl+BotxU/jOxYTr4vk/I6G/oFZyfo4ubWp2y6k/SX8r0o8EAWqNgG0K8kIlwZ1vOTK70jJ5UtNapqex+6AzWHEPKca06H2EpnOMOUUmeuedjqMARSv4KsRACSExgsp3fXvazONogGN49DcmZ+YeruCC10UV5/0WMv/Iy13J/QZRSrIwM/R5dJBR+3NPpHMwRefa46wKOXG/qzn8jfH5JdeLKNRWm+6bghz7f0lcQ6RYcR5nEZgKT1RL+cPgGocl/jQTgTTK+bP6o000nAlKIfyYVyrAwd/jm0hZTy3ItqxS5iQKBgQC+r+sGwj+dxy617MJ2ZRRmRgFNzAF4C61daM+wgllaSft7+6Nauyl/RnxVgq8QeDA8SrRX9oGcTiq0rb8e1ZHVS2H2fYBP6nryLYEN6pCsS/m/wmlTPnUVXqYMHci071emavUAoYzTfwjITSmy4wpEuia+Ale/Cg3aH8CL99WOzQKBgQCzx7biSmeMFbQJl4wTW+CBJcRQ+nPmWlGE8e563XYucko7BfiQsYkuPpOn5KW9J5LoX8R59M36YamBfGBoqIxpW72kxwQPDTHgq5b2Kr3brIbCZtXzz5rK90bmocnAAClUCb+eW3sEVyMquxsGP8BYx43anBsXK9bD0hNhHvhJowKBgQCc0nzNwC8liUwnHiIH0LVoLyafXqnOmnvnmG1GUs09bh6/JoJ/+fD01XknsiRbvRyeWSncNcT+UWLZ2RKXPzmCW06jsy81ije2uCms0j5NFOa/CBoq9fDAtGiHCm+oLja9jLUV4ca5oX4NjThAAGzPfPCjz7VuTcx6mSZ3dklR+QKBgH8qdIWKpcXkEC58wPtskNgpc7zn+5VkK6eDTfIgtpjSBQnNBm6q9eL9Joqq5EVxOawfGaY+cHh8Hl9WMAe3uWJJH1Lv50ISTkaieSz1PMinN8dI4GwOXGrXEJLQvBmQw6sLHjyQbuq6DEkMgmggLhleRkvtAgiY3Ng0v7qCIpRLAoGAdS3JjCnWJ9PrmuPWablmy6ZEn2cCcYNE5U8Wa8Mnz3d5qbN9+diJA54UuaxgQXg0KuILvdJ7fkeizatb4b22zHYGctpX81VfEd/Uu5p26bEspKQsiYhM/my1imDc1p+Q3YD+ilx8bmn8zIQN97W/0sJRQQGmqpJWUUNUM/Nvafg=
  #此处请填写你的应用公钥
  publicKey:  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhenETwvjv+aEwsRSfRfL2hD/xcBhVGiW5ri84E6pGZt8bxquUptSAF78kBIDIk1EuXEBH9CRxFr51anQajpClYeXt+l7xViGZs2O3+MV5TmFSlJ2YNcByoAR/4YjJFUzotC3b81U4xXo5AKNgHj/DoH0TAyVFXQYc8/3+mF8kCW+mhx0OlV05HfUgis9Y4s8pobu/jwtKXWKPPDN+bevmYO1ptfvYe0iv8XMc/11y2QI2qdIFef0IrxV6alrrYtUYwNLoq4nRgYsM/9t62oknZJBfSMU0o2mlX3aL5GJHJw54J/nAUbYv7LWGd2hFDo5xEvXtsZUgRjrcPMWD0phhwIDAQAB
  #异步通知url(注意拦截器是否拦截)
  notifyUrl: http://localhost:8800/notify
  #支付成功后返回的页面地址
  returnUrl: http://localhost:8080/return
